---
coverage:
  status:
    project:
      default:
        target: 90%
        removed_code_behavior: removals_only
        threshold: 1%
    patch:
      default:
        target: 50%

ignore:
  - "src/lib.rs"
  - "benches/**"
  - "examples/**"
