# rustfmt configuration for the delaunay computational geometry library
# 
# This configuration uses only stable rustfmt features to ensure compatibility
# with the project's stable Rust toolchain requirement.

# Use the same edition as Cargo.toml
edition = "2024"

# Set reasonable line width for readability across editors
max_width = 100

# Use 4 spaces for indentation (default, but explicit for documentation)
tab_spaces = 4

# Use Unix line endings for consistency
newline_style = "Unix"
