[tool.tarpaulin]
# Exclude benchmarks and examples from coverage analysis
exclude-files = [
    "benches/*",
    "examples/*",
]
# Output configuration
out = ["Xml"]
output-dir = "coverage/"
# Test configuration
all-features = true
workspace = true
timeout = 120
verbose = true
# Test execution
test-threads = 1
