name: Update Code of Conduct Timestamp

on:
  push:
    paths:
      - 'CODE_OF_CONDUCT.md'
    branches:
      - main

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update timestamp
        run: |
          # Get current date in "Month Year" format
          CURRENT_DATE=$(date +"%B %Y")

          # Update the timestamp in CODE_OF_CONDUCT.md
          sed -i "s/Last updated: .*/Last updated: $CURRENT_DATE/" CODE_OF_CONDUCT.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if there are changes to commit
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git add CODE_OF_CONDUCT.md
          git commit -m "Auto-update CODE_OF_CONDUCT.md timestamp [skip ci]"
          git push
